language: node_js
node_js:
  - "8.11.3"
  - "10.5.0"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test      
services:
  - mongodb
env:
  - NODE_ENV=test
