version: '3.6'
services:
  api:
    build:
      context: packages/wooordhunter-proxy
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/home/app
    depends_on:
      - mongo 
    env_file: .env
    command: ["yarn", "start-dev"]
  mongo:
    image: mongo:4.0.0-rc6-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
