version: '3.6'
services:
  api:
    build:
      context: packages/wooordhunter-proxy
      dockerfile: Dockerfile
    command: ["yarn", "test"]
    volumes:
      - .:/home/app
    depends_on:
      - mongo 
    environment:
      - NODE_ENV=test
      - MONGO_URL=mongodb://mongo
  mongo:
    image: mongo:4.0.0-rc6-xenial
