// flow-typed signature: 877acfac21bb54ff28eaa034f14c5e77
// flow-typed version: <<STUB>>/cherio_v^1.0.0-rc.2/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cherio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cherio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cherio/lib/api/attributes' {
  declare module.exports: any;
}

declare module 'cherio/lib/api/css' {
  declare module.exports: any;
}

declare module 'cherio/lib/api/forms' {
  declare module.exports: any;
}

declare module 'cherio/lib/api/manipulation' {
  declare module.exports: any;
}

declare module 'cherio/lib/api/traversing' {
  declare module.exports: any;
}

declare module 'cherio/lib/cheerio' {
  declare module.exports: any;
}

declare module 'cherio/lib/options' {
  declare module.exports: any;
}

declare module 'cherio/lib/parse' {
  declare module.exports: any;
}

declare module 'cherio/lib/static' {
  declare module.exports: any;
}

declare module 'cherio/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cherio/index' {
  declare module.exports: $Exports<'cherio'>;
}
declare module 'cherio/index.js' {
  declare module.exports: $Exports<'cherio'>;
}
declare module 'cherio/lib/api/attributes.js' {
  declare module.exports: $Exports<'cherio/lib/api/attributes'>;
}
declare module 'cherio/lib/api/css.js' {
  declare module.exports: $Exports<'cherio/lib/api/css'>;
}
declare module 'cherio/lib/api/forms.js' {
  declare module.exports: $Exports<'cherio/lib/api/forms'>;
}
declare module 'cherio/lib/api/manipulation.js' {
  declare module.exports: $Exports<'cherio/lib/api/manipulation'>;
}
declare module 'cherio/lib/api/traversing.js' {
  declare module.exports: $Exports<'cherio/lib/api/traversing'>;
}
declare module 'cherio/lib/cheerio.js' {
  declare module.exports: $Exports<'cherio/lib/cheerio'>;
}
declare module 'cherio/lib/options.js' {
  declare module.exports: $Exports<'cherio/lib/options'>;
}
declare module 'cherio/lib/parse.js' {
  declare module.exports: $Exports<'cherio/lib/parse'>;
}
declare module 'cherio/lib/static.js' {
  declare module.exports: $Exports<'cherio/lib/static'>;
}
declare module 'cherio/lib/utils.js' {
  declare module.exports: $Exports<'cherio/lib/utils'>;
}
